[project]
name = "filmoteka-mini-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "djangorestframework>=3.15.2",
    "djoser>=2.3.1",
    "pydantic-settings>=2.6.1",
]
